INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Alves Pereira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Amambaí', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Amantini Residence', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Arnaldino da Silva', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Arnaldo Estevão Figueiredo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bairro São Pedro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bom Retiro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bonjardim', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bosque das Araras', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bosque de Avilan', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bosque do Carvalho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bosque Santa Mônica', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Bosque Santa Mônica II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Cabreúva', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Caiçara', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Caiobá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Carandá Bosque', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Centenário', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Center Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Centro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Centro Oeste', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Chácara Cachoeira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Chácara das Mansões', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Chácara dos Poderes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Chácara Santa Abadia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Cidade Jardim', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Cohafama', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Aero Rancho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Habitacional Estrela Dalva I', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Habitacional Estrela Dalva II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Habitacional Estrela Dalva III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Habitacional Jardim Talismã', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Habitacional Nascente Segredo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Iracy Coelho III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto José Abrão', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Parati II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Residencial Botafogo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Residencial Estrela do Sul', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Residencial Octavio Pécora', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto Residencial Recanto dos Rouxinóis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Conjunto União II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coophafé', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coophamat', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coopharádio', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coophasul', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coophatrabalho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coophavila II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Coronel Antonino', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Dom Antônio Barbosa', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Edson Brito Garcia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Guanandi', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Guanandi II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Indaiá Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Itanhangá Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Aero Rancho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Aeroporto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Agulhas Negras', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Alto São Francisco', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim América', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Anache', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Antáres', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Arco Íris', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Autonomista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Auxiliadora', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Bálsamo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Barcelona', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Batistão', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Bela Vista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Bonança', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Botânico', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Botânico II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Campina Verde', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Campo Alto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Campo Belo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Campo Nobre', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Campo Verde', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Canguru', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Carioca', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Centenário', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Centro Oeste', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Colibrí', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Colonial', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Colorado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Colúmbia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Corcovado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Cerejeiras', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Hortências', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Macaúbas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Nações', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Perdizes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Reginas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim das Virtudes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim do Corrego', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim dos Estados', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Enseada dos Pássaros', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Fluminense', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Imá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Inápolis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Indianápolis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Itália', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Itamaracá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Itapuã', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Itatiaia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Jacy', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Jatobá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Jerusalem', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Jóquei Club', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Leblon', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Los Angeles', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Macapá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Manaíra', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Mansur', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Moema', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Monte Alegre', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Monte Líbano', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Monterey', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Montevidéu', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Monumento', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Morenão', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Nashiville', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Nhanhá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Noroeste', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Nossa Senhora do Perpétuo Socorro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Nova Era', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Nova Jerusalém', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Ouro Preto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Pacaembu', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Paradiso', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Parati', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Paulista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Paulo Coelho Machado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Pênfico', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Petrópolis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Polonês', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Presidente', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Radialista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Samambaia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Santa Emília', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Santa Felicidade', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim São Bento', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim São Conrado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim São Lourenço', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Sarandí', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Sayonara', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Seminário', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Sumatra', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Tarumã', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Tijuca', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Tijuca II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim TV Morena', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Uirapuru', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Veraneio', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Vida Nova', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Vida Nova II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Jardim Zé Pereira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('José Maksoud', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Lagoa da Cruz', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Lagoa Dourada', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Lagoa Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Lagoa Rica', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Lar do Trabalhador', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Alto da Boa Vista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Bosque da Esperança', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Costa Verde', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Cristo Redentor', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Dona Dedé', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento José Prates', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Marçal de Souza', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Paulo VI', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Polo Empresarial Oeste', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Porto Bello', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Praia da Urca', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Rancho Alegre II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Tarcila do Amaral', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Loteamento Vespasiano Martins', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Mata do Jacinto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Mata do Segredo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Monte Carlo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Monte Castelo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Morada do Sol', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Morada do Sossego', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Morada do Sossego II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Morada dos Deuses', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Morada Verde', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Moreninha', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Nova Lima', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Núcleo Habitacional Buriti', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Núcleo Habitacional Universitárias', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Núcleo Industrial', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Panamá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Panorama', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Atlântico', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Dallas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque do Lageado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque do Sol', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque dos Laranjais', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque dos Novos Estados', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque dos Poderes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Fazenda Imbirussu', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Isabel Gardens', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Novo Século', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial Azaléia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial dos Girassóis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial Iracy Coelho Netto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial Maria Aparecida Pedrossian', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial Rita Vieira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Parque Residencial União', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Pioneiros', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Pólo Empresarial', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Portal Caiobá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Portal Caiobá II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Portal do Panamá', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Portal Itayara', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Porto Galo', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Rancho Alegre I', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Rancho Alegre III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Rancho Alegre IV', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Recanto das Paineiras', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Recanto do Cerrado', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Recanto dos Pássaros', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Recanto Pantaneiro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residecial Nelson Trad', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Alto Tamandaré', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Ana Maria do Couto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Aquários I', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Aquários II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Atlântico Sul', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Betaville', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Búzios', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Cedrinho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Damha', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Damha II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Damha III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Estrela Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Flores', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Gama', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Hugo Rodrigues', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Ilhéus', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Joana D Arc', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Jose Teruel Filho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Mário Cóvas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Oiti', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Oliveira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Oliveira III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Pequena Flor', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Ramez Tebet', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Sírio Libanês I', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Sírio Libanês II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Sóter', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Terra Morena', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Via Park Itália', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Vida Nova III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Vila Bela', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Vila Olimpica', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Residencial Villa Lobos', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Rita Vieira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Royal Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Santa Fé', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Santo Antônio', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('São Francisco', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Sobrinho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Taquaral Bosque', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Tayamã Park', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Terras Alfha Campo Grande', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Tiradentes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Universitário', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Universitário Secção D', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Adelina', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Aimoré', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Alba', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Albuquerque', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Almeida', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Anahy', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Antônio Vendas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Bandeirante', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Base Aérea', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Belo Horizonte', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Bordon', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Carlota', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Carvalho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Célia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Cidade Morena', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Clélia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Concórdia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Danúbio Azul', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila do Polonês', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Duque de Caxias', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Eliane', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Entroncamento', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Flório', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Futurista', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Giocondo Orsi', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Glória', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Gomes', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Ieda', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Ipiranga', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Julieta', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Jussara', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Maciel', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Manoel da Costa Lima', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Manoel Sêcco Thomé', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Manoel Taveira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Marcos Roberto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Margarida', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Marli', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Matel', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Moreninha II', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Moreninha III', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Moreninha IV', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Morumbi', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nascente', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nasser', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nathália', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Neusa', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nogueira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nossa Senhora das Graças', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nova Campo Grande', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Nova Capital', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Oeste', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Olinda', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Orfeu Baís', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Palmira', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Piratininga', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Planalto', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Popular', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Progresso', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Rica', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Romana', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Rosa Pires', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Santa Dorothéia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Santa Luzia', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Santo Amaro', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Santo Eugênio', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila São Jorge da Lagoa', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila São Vicente', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Sargento Amaral', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Serradinho', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Sílvia Regina', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Taquarussu', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Taveirópolis', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vila Vilas Boas', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vivenda do Bosque', 41);
INSERT INTO `vacinasweb_db`.`bairro`(`nome`,`idCidade`)VALUES('Vivendas do Parque', 41);
