INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Água Boa', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Água Clara', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Albuquerque', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Alcinópolis', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Alto Sucuriú', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Amambaí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Amandina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Amolar', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Anastácio', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Anaurilândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Angélica', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Anhandui', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Antônio João', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Aparecida do Taboado', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Aquidauana', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Aral Moreira', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Arapuã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Areado', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Árvore Grande', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Baianópolis', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bálsamo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bandeirantes', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bataguassu', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Batayporã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Baús', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bela Alvorada', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bela Vista', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bocajá', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bocajá', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bodoquena', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bom Fim', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Bonito', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Boqueirão', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Brasilândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Caarapó', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cabeceira do Apá', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cachoeira', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Camapuã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Camisão', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Campestre', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Campo Grande', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Capão Seco', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Caracol', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Carumbé', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cassilândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Chapadão do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cipolândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Coimbra', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Congonhas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Corguinho', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Coronel Sapucaia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Corumbá', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Costa Rica', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Coxim', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cristalina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cruzaltina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Culturama', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Cupins', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Debrasa', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Deodápolis', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Dois Irmãos do Buriti', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Douradina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Dourados', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Eldorado', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Fátima do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Figueirão', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Garcias', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Glória de Dourados', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Guaçu', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Guaçulândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Guadalupe do Alto Paraná', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Guia Lopes da Laguna', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Iguatemi', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ilha Comprida', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ilha Grande', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Indaiá do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Indaiá Grande', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Indápolis', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Inocência', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ipezal', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Itahum', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Itaporã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Itaquiraí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ivinhema', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jabuti', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jacareí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Japorã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jaraguari', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jardim', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jateí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jauru', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Juscelândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Jutí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ladário', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Lagoa Bonita', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Laguna Carapã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Maracaju', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Miranda', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Montese', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Morangas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Morraria do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Morumbi', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Mundo Novo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Naviraí', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nhecolândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nioaque', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nossa Senhora de Fátima', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Alvorada do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova América', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Andradina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Casa Verde', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Esperança', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Esperança', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Nova Jales', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Novo Horizonte do Sul', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Oriente', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Paiaguás', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Palmeiras', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Pana', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Panambi', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Paraíso das Águas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Paranaíba', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Paranhos', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Pedro Gomes', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Picadinha', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Pirapora', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Piraputanga', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ponta Porã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ponte Vermelha', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Pontinha do Cocho', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Porto Esperança', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Porto Murtinho', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Porto Vilma', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Porto XV de Novembro', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Presidente Castelo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Prudêncio Thomaz', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Quebra Côco', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Quebracho', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Ribas do Rio Pardo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Rio Brilhante', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Rio Negro', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Rio Verde de Mato Grosso', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Rochedinho', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Rochedo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Sanga Puitã', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Santa Rita do Pardo', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Santa Terezinha', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São Gabriel do Oeste', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São João do Apore', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São José', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São José do Sucuriú', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São Pedro', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São Pedro', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('São Romão', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Selvíria', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Sete Quedas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Sidrolândia', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Sonora', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Tacuru', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Tamandaré', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Taquari', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Taquarussu', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Taunay', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Terenos', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Três Lagoas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Velhacaria', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vicentina', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vila Formosa', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vila Marques', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vila Rica', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vila União', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vila Vargas', 12);
INSERT INTO `vacinasweb_db`.`cidade`(`nome`,`idEstado`)VALUES ('Vista Alegre', 12);