INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'THAIS', '395');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ELAINE', '396');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'LIVIA', '397');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'GEISA', '398');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'TEODORA', '399');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'NATHALIA', '400');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'MAIRA', '401');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'josaime', '402');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'FLAVIA', '403');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'Leila', '404');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'Andressa ', '405');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ANA PATRICIA ', '406');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'GABBRIELA ', '407');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'NIVA', '408');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'LUCIANA', '409');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'FLAVIA', '410');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'MARA JOSE ', '411');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'KELLY', '412');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CARLA ROBERTA', '413');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'tassia', '414');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'SUSY', '415');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'RENATA', '416');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CAROLINA', '417');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'LAURA', '418');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ALESSANDRA', '419');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'LONDINA', '420');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'DAHIANA', '421');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'RITA', '422');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CLAUDIA ', '423');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'TASSIA', '424');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'WALKYRIA', '425');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ROSELI', '426');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'Miryan', '427');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'DIESSIKA', '428');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CAROLINE', '429');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'EDI', '430');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'LUCIANA', '431');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'INGRIDI', '432');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'GISELE', '433');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'camila', '434');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CAROLINA', '435');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'JOCIANE', '436');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'MAISA', '437');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'THIELY ', '438');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ANA BEATRIZ', '439');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'CRISTIANE', '440');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'YURI', '441');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'GESSICA', '442');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ROBERTA', '443');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ANDREIA ', '444');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'MICHELE', '445');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ALEXANDRA ', '446');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'FERNANDA', '447');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'PRISCILA', '448');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'PRISCILA', '449');
INSERT INTO `vacinasweb_db`.`paciente`(`dataCadastro`,`nomeMae`,`idPaciente`)VALUES(current_timestamp(),'ARIELLE', '450');
