/************************************************************************************************
*SQL PARA INSERIR PERMISSÕES
************************************************************************************************/

INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	1	,	'Menu principal'	,	'MENU-PRINCIPAL'); 
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	2	,	'Area Principal do sistema'	,	'MENU-PRINCIPAL-AREAPRIVADA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	3	,	'Area de descrição sobre a Clinica'	,	'MENU-PRINCIPAL-SOBRESISTEMA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	4	,	'Menu de acesso da Recepção'	,	'MENU-RECEPCAO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	5	,	'menu de acesso a Agenda'	,	'MENU-RECEPCAO-AGENDA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	6	,	'menu de acesso ao Atendimento'	,	'MENU-RECEPCAO-ATENDIMENTO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	7	,	'Menu de acesso ao cadatro do paciente'	,	'MENU-RECEPCAO-PACIENTE');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	8	,	'menu de acesso ao cadastro basico'	,	'MENU-RECEPCAO-CADASTROBASICO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	9	,	'Menu de acesso ao cadatro de Estado'	,	'MENU-RECEPCAO-CADASTROBASICO-ESTADO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	10	,	''	,	'MENU-RECEPCAO-CADASTROBASICO-CIDADE');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	11	,	''	,	'MENU-RECEPCAO-CADASTROBASICO-BAIRRO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	12	,	''	,	'MENU-SALAVACINAS');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	13	,	''	,	'MENU-SALAVACINAS-VACINACAO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	14	,	''	,	'MENU-SALAVACINAS-ESTOQUEVACINA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	15	,	''	,	'MENU-SALAVACINAS-VACINA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	16	,	''	,	'MENU-ADMINISTRACAO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	17	,	''	,	'MENU-ADMINISTRACAO-FUNCIONARIO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	18	,	''	,	'MENU-ADMINISTRACAO-TIPOFUNCIONARIO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	19	,	''	,	'MENU-ADMINISTRACAO-EMPRESA');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	20	,	''	,	'MENU-ADMINISTRACAO-ACESSO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	21	,	''	,	'MENU-ADMINISTRACAO-ACESSO-USUARIO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	22	,	''	,	'MENU-ADMINISTRACAO-ACESSO-PERFIL');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	23	,	''	,	'MENU-ADMINISTRACAO-ACESSO-PERMISSAO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	24	,	''	,	'CONSULTAR-VACINACAO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	25	,	''	,	'CONSULTAR-VACINACAO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	26	,	''	,	'CONSULTAR-VACINACAO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	27	,	''	,	'CONSULTAR-VACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	28	,	''	,	'CONSULTAR-VACINA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	29	,	''	,	'CONSULTAR-VACINA-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	30	,	''	,	'CONSULTAR-USUARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	31	,	''	,	'CONSULTAR-USUARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	32	,	''	,	'CONSULTAR-USUARIO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	33	,	''	,	'CONSULTAR-TIPOFUNCIONARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	34	,	''	,	'CONSULTAR-TIPOFUNCIONARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	35	,	''	,	'CONSULTAR-TIPOFUNCIONARIO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	36	,	''	,	'CONSULTAR-PERMISSAO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	37	,	''	,	'CONSULTAR-PERMISSAO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	38	,	''	,	'CONSULTAR-PERMISSAO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	39	,	''	,	'CONSULTAR-PERFIL-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	40	,	''	,	'CONSULTAR-PERFIL-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	41	,	''	,	'CONSULTAR-PERFIL-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	42	,	''	,	'CONSULTAR-PACIENTE-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	43	,	''	,	'CONSULTAR-PACIENTE-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	44	,	''	,	'CONSULTAR-PACIENTE-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	45	,	''	,	'CONSULTAR-LOTEVACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	46	,	''	,	'CONSULTAR-LOTEVACINA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	47	,	''	,	'CONSULTAR-LOTEVACINA-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	48	,	''	,	'CONSULTAR-FUNCIONARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	49	,	''	,	'CONSULTAR-FUNCIONARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	50	,	''	,	'CONSULTAR-FUNCIONARIO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	51	,	''	,	'CONSULTAR-ESTOQUEVACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	52	,	''	,	'CONSULTAR-ESTOQUEVACINA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	53	,	''	,	'CONSULTAR-ESTOQUEVACINA-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	54	,	''	,	'CONSULTAR-ESTADO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	55	,	''	,	'CONSULTAR-ESTADO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	56	,	''	,	'CONSULTAR-ESTADO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	57	,	''	,	'CONSULTAR-EMPRESA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	58	,	''	,	'CONSULTAR-EMPRESA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	59	,	''	,	'CONSULTAR-EMPRESA-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	60	,	''	,	'CONSULTAR-CIDADE-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	61	,	''	,	'CONSULTAR-CIDADE-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	62	,	''	,	'CONSULTAR-CIDADE-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	63	,	''	,	'CONSULTAR-BAIRRO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	64	,	''	,	'CONSULTAR-BAIRRO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	65	,	''	,	'CONSULTAR-BAIRRO-EDITAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	66	,	''	,	'MANTER-VACINACAO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	67	,	''	,	'MANTER-VACINACAO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	68	,	''	,	'MANTER-VACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	69	,	''	,	'MANTER-VACINA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	70	,	''	,	'MANTER-USUARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	71	,	''	,	'MANTER-USUARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	72	,	''	,	'MANTER-TIPOFUNCIONARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	73	,	''	,	'MANTER-TIPOFUNCIONARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	74	,	''	,	'MANTER-PERMISSAO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	75	,	''	,	'MANTER-PERMISSAO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	76	,	''	,	'MANTER-PERFIL-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	77	,	''	,	'MANTER-PERFIL-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	78	,	''	,	'MANTER-PACIENTE-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	79	,	''	,	'MANTER-PACIENTE-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	80	,	''	,	'MANTER-LOTEVACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	81	,	''	,	'MANTER-LOTEVACINA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	82	,	''	,	'MANTER-FUNCIONARIO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	83	,	''	,	'MANTER-FUNCIONARIO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	84	,	''	,	'MANTER-ESTOQUEVACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	85	,	''	,	'MANTER-ESTOQUEVACINA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	86	,	''	,	'MANTER-ESTADO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	87	,	''	,	'MANTER-ESTADO-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	88	,	''	,	'MANTER-EMPRESA-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	89	,	''	,	'MANTER-EMPRESA-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	90	,	''	,	'MANTER-CIDADE-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	91	,	''	,	'MANTER-CIDADE-DELETAR');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	92	,	''	,	'MANTER-BAIRRO-NOVO');
INSERT INTO `permissao` 	(	`idPermissao`,`descricao`,`nome`) VALUES 	(	93	,	''	,	'MANTER-BAIRRO-DELETAR');
